### ISSUE TITLE
Use different device than pdf if new_device == TRUE

### ISSUE THREAD

**Issue by flying-sheep** [hadley/evaluate#48]
the fix in #44 is awesome, but i currently have the problem that some unicode character (`⟨`) triggers some warnings in the pdf device.

and since the pdf device isn’t even used, those are totally worthless to see in my Jupyter notebook.

i end up doing

```r
options(device = function(...) png('/dev/null', ...))
```

but that’s not portable, and hackish on top (just as would be to wrap all plot calls in `suppressWarnings`)

i don’t know what can be done, since other devices don’t allow setting `filename` to NULL (`pdf` has `file` instead, whcih can be set to NULL)

**Comment by yihui** [comment]
What I ended up using was `png(tempfile())`.

**Comment by flying-sheep** [comment]
which will put unnecessary crap in my RAM :neutral_face: maybe:

```r
tmp <- tempfile()
png(tmp)
dev <- dev.cur()
on.exit({
	dev.off(dev)
	unlink(tmp)
})
```

but still, there needs to be a better solution!

**Comment by yihui** [comment]
I'm afraid `png(NULL)` is beyond the scope of this evaluate package. You may have to submit patches or file feature requests to R core if you really care about it.

**Comment by flying-sheep** [comment]
ah!

```r
options(device=function(...) pictex(NULL, ...))
plot(1, xlab='⟨')
```

this seems to work!

**Comment by yihui** [comment]
But I suspect you will not be able to record plots at all. `pictex()` is a pretty archaic device, and I don't think it is capable of recording the display list of the current plot.

**Comment by janschulz** [comment]
JFYI: on windows, `/dev/null` is `NUL` and this seems to result in the right thing (aka plots are produced in recordedplot, but no file is created). 

Executing the following code in a jupyter notebook (which uses evaluate as the backend to evaluate the code) will produce a plot:
 
```R
options(device = function(file, ...) png('NUL', ...))
plot(1:3)
```

See als here: https://github.com/IRkernel/IRkernel/issues/336

**Comment by flying-sheep** [comment]
PR: IRkernel/IRkernel#340
