### ISSUE TITLE
Use dedicated dummy device 

### ISSUE THREAD

**Issue by flying-sheep** [hadley/evaluate#51]
In e3795b1cd1cc8fd6024b2d0dca6c148c5d986f82 you test if the current device is `pdf`, i.e. the default, and then set it to a NULL file. this

1. [triggers an edge case](https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16378)
2. it makes `new_device` only work if the device is `pdf`

i propose to do this:

```r
null.file <- switch(.Platform$OS.type, unix = '/dev/null', windows = 'NUL')
dev <- getOption('device')
`%inlist%` <- function(x, l) any(vapply(l, function(e) identical(e, x), logical(1)))

#known devices with “file” as filename param
if (dev %inlist% list('pdf', pdf, ...)) dev(file = null.file)
#known devices with “filename” as filename param
else if (dev %inlist% ...) dev(filename = null.file)
...
else #proceed without opening a new device
```

**Comment by yihui** [comment]
1. That is not surprising to me. The `pdf` device does not work well with non-ASCII characters unless you carefully set up the fonts for it. Or use `cairo_pdf` or other devices.

2. You can open a graphics device before calling `evaluate(new_device = FALSE)`, or set `options(device = YOUR_OWN_DEVICE)` before calling `evaluate(new_device = TRUE)`.

I think the dummy (or null) device is beyond the scope of this package. Either base R should provide it (which is very unlikely), or the user (e.g. you) provides a custom "null" device to `evaluate()`.
