### ISSUE TITLE
evaluate package install fails

### ISSUE THREAD

**Issue by thegeologician** [hadley/evaluate#52]
Hi, when trying to install knitr or devtools, or just evaluate alone, the installation fails with a dependency problem in the evaluate package:

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/martin/R/x86_64-redhat-linux-gnu-library/3.2/stringi/libs/stringi.so':
  libicui18n.so.52: cannot open shared object file: No such file or directory

Fedora 22 Workstation, RStudio 0.99.441, R 3.2.0

output of 'locate libicui18n':
/usr/lib64/libicui18n.so
/usr/lib64/libicui18n.so.54
/usr/lib64/libicui18n.so.54.1

Might it be that I'm using too new libraries after updating to Fedora 22, and evaluate / libcui just hasn't caught up yet? How could I circumvent this without breaking future automatic updates?

**Comment by yihui** [comment]
Have you tried to reinstall the stringi package?

**Comment by thegeologician** [comment]
I had not thought of this obvious step - thank you! I could now successfully (re-)install knitr, devtools and ggplot2, which all three were stuck because of that problem in stringi... Thanks!
