### ISSUE TITLE
Allow replay() to handle NULLs

### ISSUE THREAD

**Issue by kwstat** [hadley/evaluate#53]
I was using `devtools::run_examples()` to test my package and was getting error messages about `replay()` not being able to handle an object of class `NULL`.

After much circuitous debugging, I found that I had had a custom `print()` method in my package examples that used `return()` instead of `invisible(x)`.  I have now fixed my package, but it might still be worth adding the equivalent of an `evaluate::replay.NULL` method so that `replay()` gracefully handles NULLs instead of crashing.  

While googling for help on the bug above, I found at least one other person on the web who appears to have had a similar problem.

**Comment by yihui** [comment]
Thanks! Should be fixed now.
