### ISSUE TITLE
Feature request: Add possibility to include timing information of each executed command

### ISSUE THREAD

**Issue by adamryczkowski** [hadley/evaluate#68]
I use evaluate to generate execution logs of user's R scripts, that got executed on the server.

`evaluate` is perfect to show the execution trace, but timing information is also an important debugging clue. It is tedious/impossible for each command in user script being guarded by `system.time`.

**Comment by adamryczkowski** [comment]
Bump? Can any developer at least make a comment on this? @yihui ?... 

If there are any issues with my feature I will fix them.

**Comment by yihui** [comment]
Sounds like a reasonable feature, but I don't have the time to think more about it or implement it. Sorry.
