### ISSUE TITLE
Lazy loading failed for package ‘evaluate’

### ISSUE THREAD

**Issue by jonnyrobbie** [hadley/evaluate#73]
Installing package fails

    install.packages("evaluate")

```
## Installing package into ‘/home/marek/.rkward/library’
## (as ‘lib’ is unspecified)
## trying URL 'https://cran.wu.ac.at/src/contrib/evaluate_0.10.tar.gz'
## Content type 'application/x-gzip' length 21914 bytes (21 KB)
## ==================================================
## downloaded 21 KB
## 
## * installing *source* package ‘evaluate’ ...
## ** package ‘evaluate’ successfully unpacked and MD5 sums checked
## ** R
## ** preparing package for lazy loading
## Error in dyn.load(file, DLLpath = DLLpath, ...) : 
##   unable to load shared object '/home/marek/.rkward/library/stringi/libs/stringi.so':
##   libicui18n.so.57: cannot open shared object file: No such file or directory
## ERROR: lazy loading failed for package ‘evaluate’
## * removing ‘/home/marek/.rkward/library/evaluate’
## 
## The downloaded source packages are in
## 	‘/tmp/Rtmp0HQEG6/downloaded_packages’
## Warning message:
## In install.packages("evaluate") :
##   installation of package ‘evaluate’ had non-zero exit status
```

Trying to debug the output, I see it tries to load `libicui18n.so.57` library and fails. The point is I do have this library, just in a higher version:

    $ ls /usr/lib/libicui18n*
    /usr/lib/libicui18n.so  /usr/lib/libicui18n.so.58  /usr/lib/libicui18n.so.58.2

Could the `evaluate` package not require the exact .so version (if that is really the problem)?

ok, trying to symlink `ln -s libicui18n.so libicui18n.so.57`, it now complains about `libicuuc.so.57`, so there is a bunch of libraries that are for some reason dependencies to hard versions.

```
$ R --version
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
http://www.gnu.org/licenses/.
$ uname -roms
Linux 4.8.13-1-ARCH x86_64 GNU/Linux
```

**Comment by jonnyrobbie** [comment]
Apparently, It was an issue on my side. I had to reinstall package `stringi` and now it seem to work. I apologize for spam.

**Comment by yihui** [comment]
No worries. This is certainly not the first time I have heard about the problems with the broken stringi installation. In case you run into this issue again in the future, here is my recipe to reinstall broken packages: https://github.com/yihui/xaringan/issues/2#issuecomment-264239352
