### ISSUE TITLE
evaluate losing character encoding information of arguments

### ISSUE THREAD

**Issue by jeroen** [hadley/evaluate#74]
We have been experiencing problems due to `evaluate()` losing character encoding information. 

The problem goes unnoticed on platforms that treat `unknown` as `UTF-8`. But it leads to serious interoperability problems when serializing data. It is important that the encoding bit is retained.

A minimal example that returns the correct answer for `eval()` but `evaluate()` returns `unknown`.

```r
# Some UTF-8 text
x <- c("寿司")
cl <- call('Encoding', x)

# Expected output: UTF-8
eval(cl)
## [1] "UTF-8"

# Evaluate returns 'unknown'
evaluate::evaluate(cl)
## ...
## [[2]]
## "[1] \"unknown\"\n"
```

On Windows (english) the strings even gets garbled:

```r
cl2 <- call('c', x)
eval(cl2)
## "寿司"

evaluate::evaluate(cl2)
##  "[1] \"<U+5BFF><U+53F8>\"\n"
```

**Comment by yihui** [comment]
The `Encoding(x)` does not necessarily return UTF-8. I can show you two examples:
 
On macOS with the C locale:

```bash
$ LANG="" R -e 'x <- c("寿司"); cl <- call("Encoding", x); eval(cl)'
> x <- c("寿司"); cl <- call("Encoding", x); eval(cl)
[1] "unknown"
```

On Windows with the Chinese locale:

And the problem with an English locale on Windows is known: https://github.com/hadley/evaluate/issues/59 https://github.com/hadley/evaluate/issues/66

**Comment by jeroen** [comment]
@yihui it doesn't have to be UTF-8 but I the result of `evaluate(cl)` should match that of `eval(cl)`?

**Comment by yihui** [comment]
The root problem here is that `cl` is a `call` object. We should probably just let `evaluate()` fail on such objects. What it currently does is to `deparse()` the call to get its "source" code, and evaluate the code, instead of evaluating it right away. The reason is that `evaluate()` aims to simulate REPL, which means what you need to provide to it is the source code as a character vector. For `call` objects, the source code has been lost.

**Comment by jeroen** [comment]
@yihui is there any reason we can not just evaluate given expression since it has already been parsed? I.e.: https://github.com/hadley/evaluate/pull/76

**Comment by yihui** [comment]
That is exactly what I was thinking. Let me think a bit longer about it (edge cases, Windows, etc).
